/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#a76500",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#121c2a",
        "secondary-fixed-dim": "#bdc7d9",
        "on-surface-variant": "#494454",
        "on-secondary-container": "#596373",
        "surface-container-high": "#ececec",
        "primary-fixed-dim": "#d0bcff",
        "surface-variant": "#e8e8ed",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb869",
        "surface-container-highest": "#e0e0e0",
        "inverse-surface": "#1d1d1f",
        secondary: "#6e6e73",
        "on-secondary-fixed-variant": "#3d4756",
        "on-secondary": "#ffffff",
        "on-background": "#1d1d1f",
        tertiary: "#855000",
        "inverse-primary": "#d0bcff",
        "surface-container": "#f0f0f0",
        "primary-fixed": "#ede7fb",
        "surface-dim": "#d3d3d3",
        surface: "#f5f5f7",
        "on-tertiary-fixed-variant": "#673d00",
        primary: "#6b38d4",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f5f5f7",
        background: "#f5f5f7",
        "on-tertiary-container": "#fffbff",
        "on-primary-fixed": "#23005c",
        "surface-container-low": "#fafafa",
        "surface-bright": "#f5f5f7",
        outline: "#86868b",
        "on-surface": "#1d1d1f",
        "secondary-fixed": "#d9e3f6",
        "on-primary-fixed-variant": "#5516be",
        "surface-tint": "#6d3bd7",
        "tertiary-fixed": "#ffdcbb",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#2c1700",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#fffbff",
        "primary-container": "#8455ef",
        "outline-variant": "#d2d2d7",
        "secondary-container": "#d6e0f3",
      },
      borderRadius: {
        DEFAULT: "0.75rem",
        lg: "1rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "24px",
        gutter: "24px",
        "margin-desktop": "80px",
        "container-max-width": "1280px",
        unit: "4px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-lg": [
          "18px",
          { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "1.0", letterSpacing: "0.04em", fontWeight: "500" },
        ],
        "headline-lg-mobile": [
          "36px",
          { lineHeight: "1.15", letterSpacing: "-0.025em", fontWeight: "700" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "1.3", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "display-lg": [
          "64px",
          { lineHeight: "1.05", letterSpacing: "-0.045em", fontWeight: "700" },
        ],
        "headline-lg": [
          "44px",
          { lineHeight: "1.15", letterSpacing: "-0.025em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
